// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dog.proto

/*
Package dog is a generated protocol buffer package.

It is generated from these files:
	dog.proto

It has these top-level messages:
	DogRequest
	DogResponse
*/
package dog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DogRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DogRequest) Reset()                    { *m = DogRequest{} }
func (m *DogRequest) String() string            { return proto.CompactTextString(m) }
func (*DogRequest) ProtoMessage()               {}
func (*DogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DogRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DogResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *DogResponse) Reset()                    { *m = DogResponse{} }
func (m *DogResponse) String() string            { return proto.CompactTextString(m) }
func (*DogResponse) ProtoMessage()               {}
func (*DogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DogResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DogResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*DogRequest)(nil), "dog.DogRequest")
	proto.RegisterType((*DogResponse)(nil), "dog.DogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DogService service

type DogServiceClient interface {
	GetDog(ctx context.Context, in *DogRequest, opts ...grpc.CallOption) (*DogResponse, error)
}

type dogServiceClient struct {
	cc *grpc.ClientConn
}

func NewDogServiceClient(cc *grpc.ClientConn) DogServiceClient {
	return &dogServiceClient{cc}
}

func (c *dogServiceClient) GetDog(ctx context.Context, in *DogRequest, opts ...grpc.CallOption) (*DogResponse, error) {
	out := new(DogResponse)
	err := grpc.Invoke(ctx, "/dog.DogService/GetDog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DogService service

type DogServiceServer interface {
	GetDog(context.Context, *DogRequest) (*DogResponse, error)
}

func RegisterDogServiceServer(s *grpc.Server, srv DogServiceServer) {
	s.RegisterService(&_DogService_serviceDesc, srv)
}

func _DogService_GetDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).GetDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.DogService/GetDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).GetDog(ctx, req.(*DogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dog.DogService",
	HandlerType: (*DogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDog",
			Handler:    _DogService_GetDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dog.proto",
}

func init() { proto.RegisterFile("dog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xc9, 0x4f, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xc9, 0x4f, 0x57, 0x52, 0xe0, 0xe2, 0x72, 0xc9,
	0x4f, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x4c, 0xb9, 0xb8, 0xc1, 0x2a, 0x8a,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0x29, 0x01, 0x89, 0x95, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x41,
	0xc4, 0x40, 0x6c, 0x23, 0x6b, 0xb0, 0xc1, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xba,
	0x5c, 0x6c, 0xee, 0xa9, 0x25, 0x2e, 0xf9, 0xe9, 0x42, 0xfc, 0x7a, 0x20, 0x17, 0x20, 0xec, 0x94,
	0x12, 0x40, 0x08, 0x40, 0xac, 0x50, 0x62, 0x48, 0x62, 0x03, 0xbb, 0xd0, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x4f, 0xf3, 0xac, 0xca, 0xae, 0x00, 0x00, 0x00,
}
